format_version: 2
pipelines:
  pipeline-name:
    group: group-name
    materials:
      git-repo:
        git: https://github.com/aobsedtawut/vue-gotham-todo.git
        branch: master
    stages:
      - first-stage:
          jobs:
            list:
              tasks:
                - exec:
                    command: ls
                    arguments:
                      - .
  Aob-handsome:
    group: group-name
    materials:
      git-repo:
        git: https://github.com/aobsedtawut/vue-gotham-todo.git
        branch: master
    stages:
      - install:
          jobs:
            list:
              tasks:
                - exec:
                    command: ./gotham-todo/apply-infrastructure.sh
      - build:
          jobs:
            list:
              tasks:
                - exec:
                    command: ./gotham-todo/build.sh
      - copy:
          jobs:
            list:
              tasks:
                - exec:
                    command: ./gotham-todo/copy-static-files.sh
               
