format_version: 2
pipelines:
  pipeline-name:
    group: group-name
    materials:
      git-repo:
        git: https://github.com/aobsedtawut/vue-gotham-todo.git
        branch: master
    stages:
      - first-stage:
          jobs:
            list:
              tasks:
                - exec:
                    command: ls
                    arguments:
                      - .
  aob-handsome:
    group: group-name
    materials:
      git-repo:
        git: https://github.com/aobsedtawut/vue-gotham-todo.git
        branch: master
    stages:
      - install:
          jobs:
            list:
              tasks:
                - exec:
                    command: bash
                    arguments: ./apply-infrastructure.sh
                      - .

      - build:
          jobs:
            list:
              tasks:
                - exec:
                    command: bash
                    arguments: ./build.sh
                      - .

      - Copy:
          jobs:
            list:
              tasks:
                - exec:
                    command: bash
                    arguments: ./copy-static-files.sh
                      - .
