format_version: 2
pipelines:
  pipeline-name:
    group: group-name
    materials:
      git-repo:
        git: https://github.com/aobsedtawut/vue-gotham-todo.git
        branch: master
    stages:
      - first-stage:
          jobs:
            list:
              tasks:
                - exec:
                    command: ls
                    arguments:
                      - .
  Aob-handsome:
    group: group-name
    materials:
      git-repo:
        git: https://github.com/aobsedtawut/vue-gotham-todo.git
        branch: master
    stages:
      - install:
          jobs:
            list:
              tasks:
                - exec:
                    command: yarn install
                    arguments:
                      - .

      - build:
          jobs:
            list:
              tasks:
                - exec:
                    command: yarn build
                    arguments:
                      - .

      - test:
          jobs:
            list:
              tasks:
                - exec:
                    command: yarn test
                    arguments:
                      - .
